AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MyGala Backend Occasion APIs - SAM Template

Metadata:
  AWS::ServerlessRepo::Application:
    Name: mygala-bk-occasion
    Description: MyGala Backend Occasion APIs
  cfn-lint:
    config:
      ignore_checks:
        - W3002

Parameters:
  stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment stage (dev or prod) from bk-config
  securityGroup:
    Type: String
    Description: Security group ID from bk-config
  subnet1:
    Type: String
    Description: Subnet ID 1 from bk-config
  subnet2:
    Type: String
    Description: Subnet ID 2 from bk-config
  subnet3:
    Type: String
    Description: Subnet ID 3 from bk-config
  lambdaRole:
    Type: String
    Description: Lambda execution role ARN from bk-config
  jwtSecretKey:
    Type: String
    Description: JWT secret key from bk-config
  awsRegion:
    Type: String
    Description: AWS region from bk-config
  envPrefix:
    Type: String
    Description: Environment prefix from bk-config
  awsAccountId:
    Type: String
    Description: AWS account ID from bk-config
  firebaseApp:
    Type: String
    Description: Firebase app from bk-config
  rdsDB:
    Type: String
    Description: RDS database name from bk-config
  rdsUser:
    Type: String
    Description: RDS username from bk-config
  rdsPassword:
    Type: String
    Description: RDS password from bk-config
  rdsHost:
    Type: String
    Description: RDS host from bk-config
  youtubeApiKey:
    Type: String
    Description: YouTube API key from bk-config
  geocodingApiKey:
    Type: String
    Description: Geocoding API key from bk-config
  dynamicLinksKey:
    Type: String
    Description: Dynamic links key from bk-config
  assetsBucket:
    Type: String
    Description: Assets S3 bucket from bk-config
  publicAssetsBucket:
    Type: String
    Description: Public assets S3 bucket from bk-config
  assetsCloudFront:
    Type: String
    Description: Assets CloudFront distribution URL from bk-config
  iosPackageName:
    Type: String
    Description: iOS app package name from bk-config
  iosAppStoreId:
    Type: String
    Description: iOS app store ID from bk-config
  androidPackageName:
    Type: String
    Description: Android app package name from bk-config
  apiUrl:
    Type: String
    Description: API URL from bk-config
  assetsUrl:
    Type: String
    Description: Assets URL from bk-config
  webUrl:
    Type: String
    Description: Web URL from bk-config
  redisHost:
    Type: String
    Description: Redis host from bk-config
  redisPassword:
    Type: String
    Description: Redis password from bk-config
  redisPort:
    Type: String
    Description: Redis port from bk-config
  spreadSheetId:
    Type: String
    Description: Google Spread Sheet ID from bk-config
  razorpayKeyId:
    Type: String
    Description: Razorpay key ID from bk-config
  razorpayKeySecret:
    Type: String
    Description: Razorpay key secret from bk-config
  rPaySignatureSecret:
    Type: String
    Description: RPay signature secret from bk-config

Mappings:
  StageConfig:
    dev:
      DomainName: dev-api.mygala.in
      BasePath: occasion
    prod:
      DomainName: api.mygala.in
      BasePath: occasion

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 12
    VpcConfig: !If
      - IsProdStage
      - SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds:
          - !Ref subnet1
          - !Ref subnet2
          - !Ref subnet3
      - !Ref "AWS::NoValue"
    Environment:
      Variables:
        stage: !Sub "${stage}"
        awsRegion: !Sub "${awsRegion}"
        envPrefix: !Sub "${envPrefix}"
        awsAccountId: !Sub "${awsAccountId}"
        firebaseApp: !Sub "${firebaseApp}"
        rdsDB: !Sub "${rdsDB}"
        rdsUser: !Sub "${rdsUser}"
        rdsPassword: !Sub "${rdsPassword}"
        rdsHost: !Sub "${rdsHost}"
        jwtSecretKey: !Sub "${jwtSecretKey}"
        youtubeApiKey: !Sub "${youtubeApiKey}"
        geocodingApiKey: !Sub "${geocodingApiKey}"
        dynamicLinksKey: !Sub "${dynamicLinksKey}"
        assetsBucket: !Sub "${assetsBucket}"
        publicAssetsBucket: !Sub "${publicAssetsBucket}"
        assetsCloudFront: !Sub "${assetsCloudFront}"
        iosPackageName: !Sub "${iosPackageName}"
        iosAppStoreId: !Sub "${iosAppStoreId}"
        androidPackageName: !Sub "${androidPackageName}"
        apiUrl: !Sub "${apiUrl}"
        assetsUrl: !Sub "${assetsUrl}"
        webUrl: !Sub "${webUrl}"
        redisHost: !Sub "${redisHost}"
        redisPassword: !Sub "${redisPassword}"
        redisPort: !Sub "${redisPort}"
        spreadSheetId: !Sub "${spreadSheetId}"
        razorpayKeyId: !Sub "${razorpayKeyId}"
        razorpayKeySecret: !Sub "${razorpayKeySecret}"
        rPaySignatureSecret: !Sub "${rPaySignatureSecret}"
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'platform,appversion,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,X-Firebase-AppCheck'"
      AllowOrigin: "'*'"
      AllowCredentials: false
    EndpointConfiguration:
      Type: REGIONAL
    OpenApiVersion: 3.0.1

Conditions:
  IsProdStage: !Equals [!Ref stage, "prod"]

Resources:
  # SNS Topics
  OccasionBgTasksSNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${envPrefix}-occasion-bg-tasks"

  # API Gateway with explicit stage
  OccasionApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "mygala-bk-occasion-${stage}"
      StageName: !Ref stage
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'platform,appversion,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,X-Firebase-AppCheck'"
        AllowOrigin: "'*'"
        AllowCredentials: false
      EndpointConfiguration:
        Type: REGIONAL

  # Lambda Functions
  OccasionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${envPrefix}-occasion-apis"
      CodeUri: ./
      Handler: handler.invoke
      Role: !Ref lambdaRole
      Events:
        NewOccasion:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/new
            Method: post
        ListOccasions:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/list
            Method: get
        OccasionById:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}
            Method: any
        JoinOccasion:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/join
            Method: put
        OccasionUsers:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/users
            Method: get
        OccasionAssets:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/assets
            Method: get
        OccasionInvite:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/invite
            Method: get
        OccasionUser:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/user/{userId}
            Method: put
        OccasionVendorsList:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/vendors/list
            Method: get
        OccasionAccounts:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/accounts
            Method: put

  EventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${envPrefix}-occasion-event-apis"
      CodeUri: ./
      Handler: eventsHandler.invoke
      Role: !Ref lambdaRole
      Events:
        EventList:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/event/list
            Method: get
        NewEvent:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/event/new
            Method: post
        EventById:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/event/{eventId}
            Method: any
        EventAssets:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/event/{eventId}/assets
            Method: get

  RsvpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${envPrefix}-occasion-rsvp-apis"
      CodeUri: ./
      Handler: rsvpHandler.invoke
      Role: !Ref lambdaRole
      Events:
        RsvpWeb:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/rsvp/web
            Method: post
        Rsvp:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/rsvp
            Method: any
        RsvpList:
          Type: Api
          Properties:
            RestApiId: !Ref OccasionApi
            Path: /v1/{occasionId}/rsvp/list
            Method: get

  OccasionBgTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${envPrefix}-occasion-bg-tasks"
      CodeUri: ./
      Handler: processor.sns
      Role: !Ref lambdaRole
      Timeout: 60
      Events:
        BgTasksSNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref OccasionBgTasksSNS

  # API Mapping for existing custom domain
  OccasionApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !FindInMap [StageConfig, !Ref stage, DomainName]
      RestApiId: !Ref OccasionApi
      Stage: !Sub "${stage}"
      BasePath: occasion

Outputs:
  OccasionApi:
    Description: "API Gateway endpoint URL for Occasion API"
    Value: !Sub "https://${OccasionApi}.execute-api.${AWS::Region}.amazonaws.com/${stage}/"
    Export:
      Name: !Sub "${AWS::StackName}-OccasionApi"

  OccasionFunction:
    Description: "Occasion Lambda Function ARN"
    Value: !GetAtt OccasionFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-OccasionFunction"

  EventFunction:
    Description: "Event Lambda Function ARN"
    Value: !GetAtt EventFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EventFunction"

  RsvpFunction:
    Description: "RSVP Lambda Function ARN"
    Value: !GetAtt RsvpFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RsvpFunction"